all:
  children:
    master:
      hosts:
        master1:
          ansible_host: 192.168.56.101
          ansible_user: vagrant
    worker:
      hosts:
        worker1:
          ansible_host: 192.168.56.102
          ansible_user: vagrant